### ISSUE TITLE
AppEngine ClassNotFoundException HttpException

### ISSUE THREAD

**Issue by mrschtief** [Codigami/face4j#16]
I used  new FacebookFactory(client,HttpClientType.URL_FETCH_SERVICE);
but it still tries to use commons httpclient

ClassNotFoundException: org.apache.commons.httpclient.HttpException
    at com.google.appengine.runtime.Request.process-9f68138e205ad9bb(Request.java)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    at com.face4j.facebook.http.APICallerFactory.<clinit>(APICallerFactory.java:14)

**Comment by mrschtief** [comment]
problem is the      callers.put(HttpClientType.APACHE_HTTP_CLIENT, APICaller.getInstance()); in APICallerFactory static code. it still need apache commons http even in appengine, maybe try reflection or make a version without imports of apache commons http

**Comment by nischal** [comment]
Yeah, we can change that, until then you would need to include the commons jar.
